### PR TITLE
Import tumblr

### PR DESCRIPTION
**Pull request by shapeshed**
This was completed with the jekyll-import tool but has a few issues.
- Markdown support was poor so html files were imported.
- Images are not imported so image paths link to Tumblr

Also a few points to note on this commit
- A redirect is created for the old URLs to redirect to /blog/:title. We will need to CNAME blog.pebblecode.com to pebblecode.com once this is released. The importer does this by creating an html page for the old post with a meta refresh tag.

We also need to remove `.sass-cache` and `_site` folders from the git repo as this will make it massive over time.

### CODE REVIEW

**Comment by petertait** [comment]
- Added templates for the blog page and a blog post page. 
- Added in the most recent blog posts that weren't imported over from tumblr.
- Added authors to every post because tumblr importer missed this data.

**Comment by shapeshed** [comment]
@petertait :dancer: 

this looks to have some horrible merge going on with having removed .sass-cache

It might be simpler to delete the repo and start again..

**Comment by petertait** [comment]
I think it looked worse than it was, should be a-okay now. 

Just realised we will need to make sure the 3 latest posts that weren't included in the tumblr import will need a redirect.

**Comment by shapeshed** [comment]
yeah and we'll just need to create a CNAME for blog.pebblecode.com

As it won't affect tumblr we could merge this, publish and switch over DNS at our leisure.

**Comment by petertait** [comment]
Haven't added the CNAME, but we've now got redirect on the recent posts. It's pretty much good to go when all are happy...

**Pull request merged**
