### PR TITLE
[post] Conquering PageSpeed with Jekyll

### PR DESCRIPTION
**Pull request by petertait**
Post on the process we took to improve our PageSpeed results.

### CODE REVIEW

**Comment by petertait** [comment]
WIP - don't merge just yet..

**Comment by poshaughnessy** [comment]
@petertait I noticed the pebblecode.com link at the bottom of the page 404's (because it adds pebblecode.com to the current URL). Maybe it's intentional to show off the new 404 page though? ;-D

**Comment by petertait** [comment]
Fixed! https://github.com/pebblecode/pebblecode.github.io/commit/812fcc05aabf8204e896995f9bf4a25e24c69aec

**Comment by poshaughnessy** [comment]
@petertait Ah I meant this one: "We can now sleep happy in the knowledge our visitors can zip across **pebblecode.com** in no time."

**Pull request merged**
