### PR TITLE
Post excerpts

### PR DESCRIPTION
**Pull request by JonathanUsername**
Posts in blog view now have an optional featured thumbnail property, and include a text excerpt on the blog page.

### CODE REVIEW

**Comment by shapeshed** [comment]
could you remove `.DS_Store`?

If it is not in `.gitignore` we should add it!

**Comment by JonathanUsername** [comment]
it's in .gitignore now, not sure if it was before though

**Comment by JonathanUsername** [comment]
Might need to consider layout on small screens. We should also ideally add pics for previous posts. @NiallNiall Thoughts?

**Comment by dave-hillier** [comment]
LGTM :+1:

**Pull request merged**
