### PR TITLE
Web BBQ blog post

### PR DESCRIPTION
**Pull request by poshaughnessy**

### CODE REVIEW

**Comment by poshaughnessy** [comment]
Sure thing - I'm happy to promise unlimited barbecue products, once the feature ships ;-)

**Comment by export-mike** [comment]
As long as there's heinz ketchup I'm happy

**Comment by poshaughnessy** [comment]
Darn, just realised we could've waited a few days and made this an April Fools post!

**Comment by export-mike** [comment]
Yeah I thought about this but was on the tube, by the time I had signal you'd posted it. Could always rollback?

**Comment by export-mike** [comment]
Have you tweeted it?

**Comment by poshaughnessy** [comment]
Yeah already tweeted... Oh wells!

**Comment by export-mike** [comment]
Plans for another April fools...?

**Comment by poshaughnessy** [comment]
Let's have a think!

**Comment by poshaughnessy** [comment]
I've removed the tweet and dated it April 1st now. Could help avoid confusing some of our less techy clients ;-) We'll see if anyone notices it's posted "early"!

**Pull request merged**
